### ISSUE TITLE
Sass imported files are not resolved when using src attribute

### ISSUE THREAD

**Issue by bennyschudel** [vuejs/rollup-plugin-vue#268] opened 2019-02-07 09:12 UTC
### Version
4.7.0

### Reproduction link
[https://github.com/bennyschudel/rollup-vue-sass-import-issue](https://github.com/bennyschudel/rollup-vue-sass-import-issue)

### Steps to reproduce
Add external sass file with `<style src="../styles/components/myComponent.scss" lang="scss" />` and import a file within *myComponent.scss* relative like `@import '../core';`

Then run `npm run build`

### What is expected?
core.scss could be loaded and imported

### What is actually happening?
core.scss could not be found

---
Is this a normal behaviour? Do I need to set somehow the includePaths for sass? I did not figured out the right way to do it.

**Comment by rkunev** [comment] 2019-03-11 14:37
Looks like something related to how import paths are resolved. For example this gets properly resolved and the build is successful:
```scss
@import '../styles/core';

.ui-button { /* ... */ }
```
Which to me it seems that the import statement in `/src/styles/components/UiButton.scss` is relative to the SFC component that imports it. 

For what it's worth, a regular Vue CLI app with `node-sass` & `sass-loader` installed, properly resolves `@import '../core'` so I don't think that the issue we're seeing here should be considered normal.

**Comment by TomCaserta** [comment] 2019-06-13 23:03
> For what it's worth, a regular Vue CLI app with node-sass & sass-loader installed, properly resolves @import '../core' so I don't think that the issue we're seeing here should be considered normal.

I believe the sass-loader passes through the webpack resolver as a custom resolver to node-sass which is what actually fixes this issue. It'd be interesting to see if this issue presents itself with just node-sass (or dart-sass now) alone.

**Comment by morficus** [comment] 2019-09-03 19:29
same holds true if you are trying to do an `@import` of a CSS file that is in `node_modules`.

```html
<style scoped lang="scss">
@import '~/tabulator-tables/dist/css/tabulator.min.css';

.tabulator-row.tabulator-selected {
    background-color: #769bcc;
}
</style>
```

I tried using the [alias plugin](https://github.com/rollup/rollup-plugin-alias) and [resolve plugin](https://github.com/rollup/rollup-plugin-node-resolve), but it made not difference.

**Comment by znck** [comment] 2019-11-21 16:12
Duplicate of #300

**Closed by znck** 2019-11-21 16:12 UTC
