### ISSUE TITLE
import statments inside <script> tag is failed to be resolved when re-building by watch mode

### ISSUE THREAD

**Issue by Nandiin** [vuejs/rollup-plugin-vue#234] opened 2018-09-18 12:31 UTC
### Expected behavior

import statments inside the SFC `<script>` area should be correctly resolved during a rollup rebuild triggered by the `rollup-watch`

### Actual behavior

import statments inside SFC `<script>` area is failed to be resolved.

### Steps to reproduce the behavior
1. use the `cookbook/minimal` example as the base.
2. add any valid import statement in the `<script>` area of `MyComponent.vue`
    let's say that the package imported is called `my-package` and assume that it is correctly installed inside node_modules.
3. run `npx rollup -c -w`
4. it succeeds
5. make any trivial but valid chagnes to the `MyComponent.vue` and SAVE it
6. rollup rebuilds the example but fails with `Error: Could not load my-package (imported by /path/to/the/example/MyComponent.vue?rollup-plugin-vue=script.js): ENOENT: no such file or directory, open 'my-package'`

**Comment by znck** [comment] 2018-09-22 19:55
It seems this problem is existing with rollup itself. https://github.com/rollup/rollup/issues/982

Though, I'm trying to find the root cause.

**Comment by znck** [comment] 2019-01-14 16:35
Closing in favour of similar issue #238

**Closed by znck** 2019-01-14 16:35 UTC
